"use client"

import { DocPageLayout } from "@/components/docs/doc-page-layout"
import { CodeBlockWithCopy } from "@/components/code-block-with-copy"
import { Button } from "@/components/ui/button"

const installSnippet = `npm install uploadthing
npx uploadthing init
npx nabiel-ui add file-upload`

const clientSnippet = `// Inside your component (e.g. ContactForm, MyAccount, ProductPage)
import { UploadButton } from "@/components/uploadthing"

<UploadButton
  endpoint="imageUploader"
  onClientUploadComplete={(res) => {
    console.log("Upload complete", res)
    // You can update form state, store image URL in Supabase, etc.
  }}
  onUploadError={(error) => {
    console.error("Upload failed", error)
  }}
/>`

const serverSnippet = `// app/api/uploadthing/core.ts (auto-generated by \`uploadthing init\`)

import { createUploadthing, type FileRouter } from "uploadthing/server"

const f = createUploadthing()

export const ourFileRouter = {
  imageUploader: f({ image: { maxFileSize: "4MB" } })
    .onUploadComplete(async ({ metadata, file }) => {
      console.log("Uploaded file:", file.url)
      // Store file.url in your database (e.g. Supabase)
    }),
} satisfies FileRouter

export type OurFileRouter = typeof ourFileRouter`

export function uploadthingDoc() {
  return (
    <DocPageLayout
      title="UploadThing Integration for File Uploads"
      description={
        <>
          This guide shows how to use <code>UploadThing</code> with components like{" "}
          <code>{"<ContactForm />"}</code>, <code>{"<MyAccount />"}</code>, or{" "}
          <code>{"<ProductPage />"}</code> to upload images or files.
        </>
      }
      addSnippet={installSnippet}
      usageSnippet={clientSnippet}
      preview={
        <div className="flex flex-col items-center space-y-4">
          <Button onClick={() => alert("This would open the UploadThing file picker.")}>
            Simulate UploadThing Button
          </Button>
          <p className="text-sm text-muted-foreground text-center">
            This simulates uploading a file using UploadThing’s smart file picker.
          </p>
        </div>
      }
      extraNotes={
        <>
          <h3 className="text-lg font-semibold mt-6 mb-2">🧩 Add to Any Component</h3>
          <p className="text-sm text-muted-foreground mb-2">
            The <code>{"<UploadButton />"}</code> can be used in:
          </p>
          <ul className="list-disc pl-5 text-sm text-muted-foreground space-y-1">
            <li><code>ContactForm</code> – to attach screenshots or documents</li>
            <li><code>MyAccount</code> – for uploading profile photos</li>
            <li><code>ProductPage</code> – to upload product images or samples</li>
            <li><code>TrackOrder</code> – to upload proof of delivery or support documents</li>
          </ul>

          <h3 className="text-lg font-semibold mt-6 mb-2">🔐 Server Setup</h3>
          <CodeBlockWithCopy code={serverSnippet} />

          <h3 className="text-lg font-semibold mt-6 mb-2">🛠️ Add Upload Handler</h3>
          <p className="text-sm text-muted-foreground mb-2">
            After running <code>uploadthing init</code>, you'll have:
          </p>
          <ul className="list-disc pl-5 text-sm text-muted-foreground space-y-1">
            <li><code>app/api/uploadthing/core.ts</code> for server upload logic</li>
            <li><code>uploadthing.config.ts</code> for router setup</li>
            <li>A working default <code>imageUploader</code> endpoint</li>
          </ul>

          <h3 className="text-lg font-semibold mt-6 mb-2">🌐 Frontend Wrapper</h3>
          <CodeBlockWithCopy
            code={`import { UploadButton } from "@/components/uploadthing"

export function FileUploadDemo() {
  return (
    <UploadButton
      endpoint="imageUploader"
      onClientUploadComplete={(res) => {
        console.log("Upload complete:", res)
      }}
      onUploadError={(err) => {
        console.error("Upload error:", err)
      }}
    />
  )
}`}
          />

          <h3 className="text-lg font-semibold mt-6 mb-2">📘 Resources</h3>
          <ul className="list-disc pl-5 text-sm">
            <li>
              <a
                href="https://docs.uploadthing.com/"
                className="underline"
                target="_blank"
              >
                UploadThing Docs
              </a>
            </li>
            <li>
              <a
                href="https://docs.uploadthing.com/quickstart"
                className="underline"
                target="_blank"
              >
                UploadThing Quickstart
              </a>
            </li>
            <li>
              <a
                href="https://github.com/pingdotgg/uploadthing"
                className="underline"
                target="_blank"
              >
                GitHub Repo
              </a>
            </li>
          </ul>
        </>
      }
    />
  )
}
